### PR TITLE
Opening hours in compose

### LINKED ISSUE #6175: on resurvey, more complex but valid opening_hours are zeroed-out, and user is required to enter them from scratch
(Opening a new issue as suggested in https://github.com/streetcomplete/StreetComplete/issues/6164#issuecomment-2731495036)

**How to Reproduce**
- open a node which has a more complex opening_hours which are due to resurvey (as e.g. [node 1990156785](https://www.openstreetmap.org/node/1990156785)  with valid `opening_hours` of [Mo-Su 06:00-22:00; Jun-Sep Mo-Su 06:00-24:00; PH off](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Su%2006%3A00-22%3A00%3B%20Jun-Sep%20Mo-Su%2006%3A00-24%3A00%3B%20PH%20off&lat=45.2693&lon=16.9102&mode=0&DATE=1742271240000)). Note that having default opening_hours  which are overriden in summer (as in that example) is common practice at least in summer-tourism-bound countries like Croatia (and is signed as such on the doors: having a regular opening hours sign, and then an additional sign with "override" for summer / holidays).
- see that resurvey quest kicks-in
- however, clicking on the quest user is presented with zeroed-out (empty) opening_hours. That is both annoying to the user (who has to engage in complex task of filling-in data from scratch) and damaging to existing data (which was likely more precise and versatile then what user will enter via SC on such resurvey).

https://github.com/user-attachments/assets/af65d4e3-7244-4309-9990-e460a7c3e5b5

**Expected Behavior**
From more preferred at the top to less preferred at the bottom:

- ideally, I would expect the SC to parse those `opening_hours`, and present it for editing to user in SC-compatible format (e.g. as `Oct-May Mo-Su 06:00-22:00; Jun-Sep Mo-Su 06:00-24:00; PH off` in this case). That way, user could detect and correct any inaccuracies in existing UI, while the data would remain preserved.
- if that is too complex,  I would expect that SC would **skip resurvey** on such opening_hours that are too complex for it to handle. (i.e. do not needlessly zero-out valid existing data)
- or, at the very least, to warn that it is about to nuke existing valid opening_hours if the user proceeds with updating.

**Versions affected**
SC 60.3, Android 14

### LINKED ISSUE #6646: Collection times can be time range but only specific point of time supported
In Hungary, post boxes have time range as collection times, but StreetComplete supports only specific point of time. Here is how it is written on a post box:

Image

The Hungarian text `PÉNTEK 18-20 között` is `On FRIDAY between 18:00-20:00`. With using StreetComplete, mappers can add this as `Fr 18:00,20:00` instead of `Fr 18:00-20:00`. Some mappers add only `Fr 18:00` because of this bug.

Can you please enable time ranges for Hungary?

**How to Reproduce**
Visit a post box in Hungary and read the collection times. It is always a time range of 2 hours instead of a specific pont in time.

**Expected Behavior**
Mappers can add the written time range.

**Versions affected**
Current

### PR DESCRIPTION
**Pull request by westnordost**
### Re-did in compose:

- opening hours quest
- postbox collection times quest
- parking fee quests (because it contains a opening hours form)

also fixes #6646, fixes #6175

### Changes made to UI:
- don't write "16:00+" but "from 16:00"
- don't write "16:00-20:00+" but "16:00-20:00 until late"
- better localization:
  - times are shown fully localized, also in the picker. E.g. in French-speaking Canada, times are commonly written like "16h00", in Korean, "오후 04:00", in Bulgarian, "16:00 ч.", in Dzongkha (Bhutan) "ཆུ་ཚོད་ 04  སྐར་མ་  00 ཕྱི་ཆ་", etc...
  - in enumerations (e.g. "Mo, Tu, Fr-Su..."), use the correct comma / range character depending on the locale. E.g. in Japan, the range character is "～", in Chinese, Japanese etc. the comma is "、"
- in postbox collection quest, can now select that actually a time range is specified (#6646)
- when specifying by months, must always specify *some* month (not allowed to leave blank) (#6175)
- bit wider buttons so it is easier to tap on the opening hours elements
- uses own wheel-picker based time picker now (i.e. not the dial-picker from android)
  - when adding times, picker defaults to a likely default time (so user has to scroll less or not at all): `9:00-18:00` for the first time for new weekdays, or one hour after the end of the previous time for existing weekdays

### Screenshots

Re-survey
Screenshot_20260118_222642

with months
Screenshot_20260118_222611

dialogs (in Germany, with English locale)
Screenshot_20260118_222919
Screenshot_20260118_222907
Screenshot_20260118_222935

(parking) fee form: maxstay and restricted by times

[Screen_recording_20260119_000908.webm](https://github.com/user-attachments/assets/4d4ef6ea-191c-445b-9845-0f9456ad093c)

[Screen_recording_20260119_000935.webm](https://github.com/user-attachments/assets/35b19948-95f6-41b0-b3e7-7b86e6f6c8fc)

### CODE REVIEW

**Comment by paulklie** [comment]
"no regular opening hours" seems to crash the app.

**Comment by paulklie** [comment]
Also: if you add months, then (accidentally) remove them, you cannot bring them "back" again: The "it differs by month" button does not do anything.

Looks really cool though, nice work!

**Comment by westnordost** [comment]
Thanks for the bug reports!

**Comment by westnordost** [comment]
(I will be on vacation for several weeks starting after this weekend, so this PR will be open for some more time. I also plan to release a bugfix release before my vacation.)

**Comment by paulklie** [comment]
> (I will be on vacation for several weeks starting after this weekend, so this PR will be open for some more time. I also plan to release a bugfix release before my vacation.)

ok! will try to triage a bit more until then

**Comment by westnordost** [comment]
Alright, all done, including self-review. I'll merge it when I am back from vacation.

**Comment by westnordost** [comment]
That the popup menu / dropdown menu appears at the wrong location is somewhat... well, expected, or a known issue, see #6665

**Comment by kmpoppe** [comment]
Just a quick point, while I'm out and about as well and wholly unable to read 3.8k changed lines (sorry!)

https://github.com/streetcomplete/StreetComplete/blob/master/app%2Fsrc%2FcommonMain%2Fkotlin%2Fde%2Fwestnordost%2Fstreetcomplete%2Fosm%2Fopening_hours%2Fmodel%2FTimeRange.kt#L32-L43

This creates "open end" answers like 16:00-20:00+ because you can't not select a time picker answer in the "closing time" dialog. Is that intentional? There might simply be no "minimum opening hours that could be extended", which is how I would read the above example?

Edit: oh, I'm supposed to pick the opening time as the closing time to get the result I was aiming for... This feels weird 🙃

K

**Comment by westnordost** [comment]
this works as before. If you specify the same start and end time, it will set it to e.g. 16:00+

**Comment by paulklie** [comment]
The "drop down" menu with the "Add days of the week" and "Add off days" options is in the top right corner for me. Is this intentional?

**Comment by FloEdelmann** [comment]
@paulklie Yes, see https://github.com/streetcomplete/StreetComplete/pull/6691#issuecomment-3767965276.

File: app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+                    LocalContentAlpha provides ContentAlpha.medium,
+                    LocalTextStyle provides MaterialTheme.typography.body2
+                ) {
+                    Text(stringResource(Res.string.quest_openingHours_comment_description))
+                }
+                TextField(
+                    value = comment,
+                    onValueChange = {
+                        val noDoubleQuotes = it.replace("\"", "").trim()
+                        if (noDoubleQuotes.length < 253) comment = noDoubleQuotes
```
Comment (Helium314) [inline app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt:72]: @westnordost did you mean `if (noDoubleQuotes.length < 253) comment = it`?
In the current state you can't enter double quotes or space.

Comment (westnordost) [reply app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt:72]: oops! Thank you!

Comment (westnordost) [reply app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt:72]: no, wait, where is the problem? Yes, no double quotes are allowed in the opening hours comment. And only whitespace at the start or end is not allowed.

Comment (westnordost) [reply app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt:72]: ah... I get it

Comment (westnordost) [reply app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt:72]: done

Comment (FloEdelmann) [reply app/src/commonMain/kotlin/de/westnordost/streetcomplete/ui/common/opening_hours/OpeningHoursCommentDialog.kt:72]: For reference: 22581e1022b20206afe66b8bde5acecdebf86d1b
