### PR TITLE
Cycleway overlay

### LINKED ISSUE #4634: Crash when adding a parking lane
The crash only happens with a specific way, but is deterministic.

**How to Reproduce**
* Select this way in the parking lane overlay: https://www.openstreetmap.org/way/4014978
* Then select the south side and add “parallel on street side” (screenshot below). Leave the north side as-is.
* The app crashes when confirming.

**Expected Behavior**
I would expect the app to add the information I gave to the map.

Alternatively, if the way was not meant to be added a parking lane, then I would not expect the app to let me select it in the first place.

**Additional information**
Screenshot:
Screenshot_2022-11-15-10-45-48-614_de westnordost streetcomplete

Here is the backtrace that I get:
```
java.lang.IllegalArgumentException: Attempting to tag invalid parking lane
	at de.westnordost.streetcomplete.osm.street_parking.StreetParkingKt.toOsmLaneValue(StreetParking.kt:122)
	at de.westnordost.streetcomplete.osm.street_parking.StreetParkingKt.applyTo(StreetParking.kt:92)
	at de.westnordost.streetcomplete.overlays.street_parking.StreetParkingOverlayForm.onClickOk(StreetParkingOverlayForm.kt:136)
	at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.onViewCreated$lambda-6(AbstractOverlayForm.kt:194)
	at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.$r8$lambda$18Xv-GzCmBt76jzZFt341LP4EVc(AbstractOverlayForm.kt)
	at de.westnordost.streetcomplete.overlays.AbstractOverlayForm$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass)
	at android.view.View.performClick(View.java:5647)
	at android.view.View$PerformClick.run(View.java:22465)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

Here are the keys of the way in question:
```
highway=service
maxspeed=30
name=Rue Eugène Chavant
parking:lane:both=parallel
surface=asphalt
```

The reason why I leave the north side as-is is that there is a discrepancy between what is meant to be and what there is: according to what the signs says, it should be `parking:lane:left=no`, but in practice people will informally park there where they can, so it’s more like `parking:lane:left=parallel`, `parking:lane:left:parallel=half_on_kerb`, leaving no actual space for pedestrians.
If the goal of this key is to measure the space dedicated to cars, I guess that the second would be more useful (as this part of the street is filled with cars), but if the goal is to tell drivers where to safely park, the first version is preferable. If we add to this the fact that the town actually uses OSM maps, then drivers could start complaining against fines because the town maps says so.
So really, there is no solution that I’m comfortable with about the north side of the street. The south is clear though, hence my answer ☺

**Versions affected**
Android version: 7.1.2 N2G47H
Kernel version: 3.18.31-perf-g6507e5c
StreetComplete version: v49.0

### PR DESCRIPTION
**Pull request by westnordost**
- refactored cycleway, street parking and sidewalk parsers to be be consistent and properly handle all edge cases when tagging only one side (fixes #4634). A side-effect of this is that the app will always merge same `*:left` and `*:right` values to `*:both` as was requested several times somewhere in this issue tracker and where I was like 🤷 before.
- refactored cycleway quest to share as much code with the overlay as possible
- fixed a bug in cycleway parsing: If in flow direction of a oneway there was a dual track or dual lane and in contra-flow direction there was nothing, the parser would wrongly interpret the contra-flow side as being "none, no oneway", i.e. as if bicycles could go in contraflow on the street itself
- made cycleway parser more strict: The parser does not accept values like `on_street`, `none` etc. anymore / classifies them as `INVALID` rather than `UNKNOWN`
- disabled cycleway quest
- added `cycleway=shoulder` option for overlay and quest (see [discussion](https://community.openstreetmap.org/t/rare-cycleway-value-shoulder-obsolete-or-useful/5849))
- sidewalk overlay: do not show missing sidewalks on roads with a speed limit <= 10 km/h and unpaved roads as missing
- sidewalk overlay: show sidewalks mapped on cycleways, paths etc
- sidewalk overlay: allow editing of sidewalks mapped on exclusive cycleways
- sidewalk overlay: prefer tagging `sidewalk:both=separate` over `sidewalk=separate`

### Features of the overlay

Display and change cycleway layout.
- Cycleways behind the curb are blue-ish (a track, a shared sidewalk)
- Lanes on the street are yellow-ish
- Black is none
- Red is missing, invalid or ambiguos.

Display bicycle boulevards, can be selected instead of defining cycleways left and right in countries where they exist legally, see [hasBicycleBoulevard.yml](https://github.com/streetcomplete/countrymetadata/blob/master/data/hasBicycleBoulevard.yml)

Change the cycleway situation on separately mapped ways and paths.

https://user-images.githubusercontent.com/4661658/204665892-cdda5758-21c4-47d3-88d8-469f2088b218.mp4

Display and select to reverse the direction of cycleways (functionality also added to respective quest). 

This was necessary because the quest could ignore (=not show) roads tagged with such cycleways, while the overlay must support it in order to not overwrite the data with wrong data.

Yes, this very rarely actually happens, see
https://www.openstreetmap.org/way/1032480826
https://www.google.de/maps/@40.6761578,-73.9508024,3a,75y,266.58h,74.83t/data=!3m6!1e1!3m4!1snlCNLeAEszlMGEmNGcfURA!2e0!7i16384!8i8192

This required a large refactor, because the parser that reads the OSM data, the creator that puts the data model back into the tags and all of the display code needs to handle pairs of cycleway type + cycleway direction. Before, it just had to handle the cycleway type.

### CODE REVIEW

**Comment by westnordost** [comment]
Would anyone like to help by reviewing this code? @Helium314 @matkoniecz @FloEdelmann

**Comment by Helium314** [comment]
> Would anyone like to help by reviewing this code? @Helium314 @matkoniecz @FloEdelmann

Currently I don't have much time available, maybe in a week or so if the PR is still open then...

File: app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+    override val changesetComment = "Specify whether there are cycleways"
+    override val wikiLink: String = "Key:cycleway"
+    override val achievements = listOf(EditTypeAchievement.BICYCLIST)
+    override val hidesQuestTypes = setOf(AddCycleway::class.simpleName!!)
+
+    override fun getStyledElements(mapData: MapDataWithGeometry) =
+        // roads
+        mapData.filter("""
+            ways with
+              highway ~ motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|living_street|pedestrian|service
```
Comment (matkoniecz) [inline app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt:47]: there are cases of cycleway lanes on motorways

yes really, see https://osmus.slack.com/archives/C029HV951/p1653292353895499

Also, technically `cycleway=track` is still valid there.

**Comment by matkoniecz** [comment]
`bicycle = use_sidepath` should remove red "data missing highlight" ( https://www.openstreetmap.org/way/168660721 )

segregated cycle and footway vs segregated by kerb - at least in Poland both are tagged in the same way. See https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg that would be tagged

```
    highway=path
    segregated=yes
    foot=designated
    bicycle=designated
    surface=paved
    cycleway:surface=asphalt
    footway:surface=paving_stones
```

**Comment by matkoniecz** [comment]
"not designated for cyclists" is not being clear that it includes both "situation unclear" and "clear cycling permission" (for example in park with rule allowing cycling) and "clear ban on cycling" (again, in some parks)

**Comment by matkoniecz** [comment]
red highlight seems quite aggressive in general and seems asking to add data that seems not really needed - is there a real benefit of `no` tagging added in https://www.openstreetmap.org/changeset/129557275 ?

**Comment by matkoniecz** [comment]
Overall: promising to be very powerful tool! Looks great!

One thing that may benefit from some extra tweaking: is it possible to easily distinguish between `highway=residential oneway=yes` (oneway also for cyclists) and one that is not limited in such way?

File: app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt (hunk 1 above)
Comment (westnordost) [reply app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt:47]: Hm. I guess it could be treated the same as `motorway_link` and `motorroad`. Do not show as missing, but allow editing.

Though, I wonder which outweighs the other:
- Being able to tag correctly the rare case of a `cycleway` on a motorway (and be it `cycleway=separate`)
- or the addition of wrong cycleway data on motorways due to human errors
?

Comment (matkoniecz) [reply app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt:47]: > or the addition of wrong cycleway data on motorways due to human errors

how likely is that user will not spot such mistake?

Also, at least following would apply:

- being able to visualise already tagged info
- being able to remove already badly tagged data on motorways due to human errors

**Comment by westnordost** [comment]
Thank you for taking the time to scan through the PR!

> "not designated for cyclists" is not being clear that it includes both "situation unclear" and "clear cycling permission" (for example in park with rule allowing cycling) and "clear ban on cycling" (again, in some parks)

Do you have an idea for a clearer wording? Also, what exactly do you find unclear? What situation could you think of where the user would tap the wrong selection?

> red highlight seems quite aggressive in general and seems asking to add data that seems not really needed - is there a real benefit of no tagging added in https://www.openstreetmap.org/changeset/129557275 ?

Yeah, why not? Is it unreasonable to assume that there _could_ be a cycleway in a residential street?

> bicycle = use_sidepath should remove red "data missing highlight" ( https://www.openstreetmap.org/way/168660721 )

You mean, `bicycle=use_sidepath` should be understood as synonymous to `cycleway=separate` in this context? But in which direction? I.e. `cycleway:left=separate` or `both` or `right`? Even if it is accepted as a synonym, it would still be "data missing" as it is ambiguous to which side it refers to, wouldn't it?

> segregated cycle and footway vs segregated by kerb - at least in Poland both are tagged in the same way. See https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg that would be tagged

Hm yeah, that tagging is fine too, but since there are over 20000 sidewalks tagged on cycleways, the sidewalk option must be supported, too. And we can't have different tagging rules in different countries only because it is not common to tag cycleways with sidewalks in that country.
If a cycleway is segregated from the footway with an actual kerb, I think it is fair to tag it as a sidewalk, as the degree of segregation is somewhat stronger.

File: app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt (hunk 1 above)
Comment (westnordost) [reply app/src/main/java/de/westnordost/streetcomplete/overlays/cycleway/CyclewayOverlay.kt:47]: Right, okay. I will add motorway

**Comment by matkoniecz** [comment]
> Do you have an idea for a clearer wording? 

Add "cycling may be allowed or banned"?

> Also, what exactly do you find unclear?

For me it was relatively clear but typical user will not see difference between "cycling allowed" and "designated for cycling"

> What situation could you think of where the user would tap the wrong selection?

park paths where cycling is legal

https://www.openstreetmap.org/way/154078492

https://commons.wikimedia.org/wiki/File:Autumn_in_Decjusz_Park.jpg

Or (in Poland) >2m wide sidewalks next to roads allowing >50km/h speeds.

> You mean, bicycle=use_sidepath should be understood as synonymous to cycleway=separate in this context? 

yes

> But in which direction?

like with `cycleway=separate` it is not foolproof, but either way strongly asking for data is not really useful

> it would still be "data missing" as it is ambiguous to which side it refers to, wouldn't it?

not for dual carriageway roads and roundabouts

Note that I am not proposing to block data entry, just to remove red highlight

>  since there are over 20000 sidewalks tagged on cycleways, the sidewalk option must be supported, too

I think that it is strongly localized to Netherlands but investigating this may be a good idea.

The problem is that at least in Poland noone thinks about this construction as "cycleway with sidewalk" but as "cycleway on sidewalk of a road" and noone tags it this way. And StreetComplete with current description claims that such currently well tagged objects are tagged incorrectly

**Comment by matkoniecz** [comment]
> Yeah, why not? Is it unreasonable to assume that there could be a cycleway in a residential street?

in general yes, except `oneway=yes` ones where contraflow lane or contraflow without lane is likely.

Especially `maxspeed=30` roads are really unlikely to have separate cycleways at least in my area

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -1570,7 +1570,7 @@ Partially means that a wheelchair can enter and use the restroom, but no handrai
     <string name="bicycle_boulevard">Bicycle boulevard</string>
     <string name="separate_cycleway_no">No cycling</string>
     <string name="separate_cycleway_allowed">Cyclists are admitted</string>
-    <string name="separate_cycleway_no_or_allowed">Not designated for cyclists (regardless of whether they are admitted or prohibited) </string>
+    <string name="separate_cycleway_no_or_allowed">Not designated for cyclists (regardless of whether cycling is admitted or prohibited) </string>
```
Comment (matkoniecz) [inline app/src/main/res/values/strings.xml:1573]: maybe "permitted" or "allowed"? "admitted" seems less clear

Comment (westnordost) [reply app/src/main/res/values/strings.xml:1573]: For the string above there too then?

Comment (westnordost) [reply app/src/main/res/values/strings.xml:1573]: "Admit" sounds more like "allowed as a guest", which is why I chose that word

Comment (matkoniecz) [reply app/src/main/res/values/strings.xml:1573]: > For the string above there too then?

Yes

**Comment by westnordost** [comment]
>> But in which direction?
>
> like with cycleway=separate it is not foolproof, but either way strongly asking for data is not really useful
>
>>  it would still be "data missing" as it is ambiguous to which side it refers to, wouldn't it?
>
> not for dual carriageway roads and roundabouts
>
> Note that I am not proposing to block data entry, just to remove red highlight

So let's say there is `bicycle=use_sidepath` on a one-way street. When tapping on it, it is displayed as "separate" on both sides. The user continues with changing the left side of the oneway road from "separate" to "no". The app then tags `cycleway:left=no`, `cycleway:right=separate`. What should the app do with `bicycle=use_sidepath`? Delete it? Keep it? Keep it even if the user ends up selecting something not-separate for both sides?

**Comment by westnordost** [comment]
> I think that it is strongly localized to Netherlands but investigating this may be a good idea.

> The problem is that at least in Poland noone thinks about this construction as "cycleway with sidewalk" but as "cycleway on sidewalk of a road" and noone tags it this way. And StreetComplete with current description claims that such currently well tagged objects are tagged incorrectly

What if there is a kerb **BETWEEN** the cycleway and the footway?

**Comment by matkoniecz** [comment]
> So let's say there is bicycle=use_sidepath on a one-way street. 

Is it oneway for cyclists? Then

**Comment by matkoniecz** [comment]
> > I think that it is strongly localized to Netherlands but investigating this may be a good idea.

> > The problem is that at least in Poland noone thinks about this construction as "cycleway with sidewalk" but as "cycleway on sidewalk of a road" and noone tags it this way. And StreetComplete with current description claims that such currently well tagged objects are tagged incorrectly

> What if there is a kerb **BETWEEN** the cycleway and the footway?

also then, see https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg with kerb between cycleway and footway

**Comment by westnordost** [comment]
>> So let's say there is bicycle=use_sidepath on a one-way street.

> Is it oneway for cyclists? If yes, then " it is displayed as "separate" on both sides" would be wrong

Wouldn't `biycle=use_sidepath` then not also be wrong? Should it not be `bicycle:forward=use_sidepath` instead?
Why should `biycle=use_sidepath` not be ambiguous on a one-way street when `cycleway=separate` is on a one-way street?
Anyway, you didn't regard the rest of my comment.

**Comment by matkoniecz** [comment]
> Wouldn't biycle=use_sidepath then not also be wrong? Should it not be bicycle:forward=use_sidepath instead?

I think that it is not needed. `oneway=yes` without `oneway:bicycle=no` already means that contraflow bicycle traffic is fully banned.

`bicycle:forward=use_sidepath` could be used, but also `motor_vehicle=destination` is fine even if `motor_vehicle:forward=destination` would also work (as travel in opposite direction is fully blocked by road being oneway)

>  Why should biycle=use_sidepath not be ambiguous on a one-way street when cycleway=separate is on a one-way street?

`bicycle=use_sidepath` applies to directions (usually both forward and backward, though here backward is excluded by `oneway=yes`). `cycleway=separate` applies to side (and is a bit underdefined as may apply to left, right or both)


------------

Lets now consider `oneway=yes bicycle=use_sidepath oneway:bicycle=no`

> So let's say there is `bicycle=use_sidepath` on a one-way street. When tapping on it, it is displayed as "separate" on both sides. The user continues with changing the left side of the oneway road from "separate" to "no". The app then tags `cycleway:left=no`, `cycleway:right=separate`. What should the app do with `bicycle=use_sidepath`? Delete it? Keep it? Keep it even if the user ends up selecting something not-separate for both sides?

In this case I would argue that this tagging typically does not really makes sense.

`bicycle=use_sidepath` means that cycling there is not legal as cyclists should use separately mapped cycleway (and applies, as access tag in both directions)

`oneway:bicycle=no` means that cycling is allowed in both directions on this object.

Very technically it could be possible in case where cycling on road is necessary to get into some specific direction(s) but otherwise you are obligated to use cycleways present along the road.

I do not see a good way to present using existing features of SC cycleway overlay.

**Comment by westnordost** [comment]
So, how about StreetComplete never touches `bicycle=use_sidepath` when tagging but when parsing, interprets `bicycle=use_sidepath` as `cycleway:both=separate` in case an explicit `cycleway` tag is missing?

I.e. pseudo code

```kotlin
val left =
  tags["cycleway:left"]
  ?: tags["cycleway:both"]
  ?: tags["cycleway"]
  ?: (if (tags["bicycle"]=="use_sidepath") "separate" else null)
```

---

on cycleways with sidewalks:

> also then, see https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg with kerb between cycleway and footway

Yes, preferences aside, I'd see it as not a mistake to tag this as `highway=cycleway + sidewalk=left`. Certainly, neither common in my area as far as I know, but removing this option only because it is not common to tag it like that in that area is bs.

**Comment by matkoniecz** [comment]
The problem is that SC currently describes current tagging as wrong.

**Comment by westnordost** [comment]
> The problem is that SC currently describes current tagging as wrong and incorrect.

How so?

> Segregated cycle- and footway
> Exclusive cycleway with sidewalk (footway is segregated from cycleway by a kerb)

**Comment by matkoniecz** [comment]
cycleway + footway (footway segregated from cycleway by a kerb) will be listed with "Segregated cycle- and footway" rather than "Exclusive cycleway with sidewalk (footway is segregated from cycleway by a kerb)"

In effect SC claims that correct action is to retag them as cycleway with sidewalk.

**Comment by westnordost** [comment]
No, it just claims that both descriptions fit the situation. And this is correct, because the situation can be tagged both ways. 

And in case there really is a kerb between sidewalk and cycleway, it is actually a more precise description.

I am kind of surprised that your main line of argumentation seems to come from the point of view that the tagging of one and the same physical situation should be adapted to how things are commonly tagged in a certain region because I do not consider this view as defensible at all in a global project with global tagging scheme. And I thought we'd be on the same page here.

**Comment by matkoniecz** [comment]
> I am kind of surprised that your main line of argumentation seems to come from the point of view that the tagging of one and the same physical situation should be adapted to how things are commonly tagged in a certain region because I do not consider this view as defensible at all in a global project with global tagging scheme.
> So far, I thought we'd be on the same page on that general realization.

I agree, but I treat `sidewalk` tagging as local aberration not worth promoting, rather than as preferable tagging for this feature.

(maybe it is not justified in this case, but I still cannot bring myself to treat such footway as sidewalk of cycleway while footway and cycleway are together sidewalk of a road)

**Comment by matkoniecz** [comment]
Out of 2 000 000 cycleway segments.

https://taginfo.openstreetmap.org/tags/building=collapsed tagging for renderer is used 70 000 times.

File: app/src/main/res/values/strings.xml (hunk 2 above)
Comment (ZeLonewolf) [reply app/src/main/res/values/strings.xml:1573]: I believe "allowed" is what you want.  "Admitted" is a formal way to say "allowed entry into" and would typically be used in cases where someone is showing a ticket for admission.

**Comment by matkoniecz** [comment]
> Local "aberration" or not, software that processes OSM data needs to support this, doesn't it? StreetComplete cannot come about and just overwrite such cases with segregated=yes and thus destroy data.

I agree, but would it be possible to not show this two as distinct options?

**Comment by westnordost** [comment]
Hmm, that should be possible. You probably mean that however it is tagged, leave it as is if the user does not change the selection and if it is selected newly, always tag it with `segregated`.

In case you also digged through some past discussion, can you link one where the consensus was something along these lines? (I.e. "eh, no, we do not want sidewalk on cycleways generally even if there are kerbs")

**Comment by matkoniecz** [comment]
> You probably mean that however it is tagged, leave it as is if the user does not change the selection and if it is selected newly, always tag it with segregated.

yes - though there is a risk that people in Netherlands are going to be unhappy about that in turn


> In case you also digged through some past discussion, can you link one where the consensus was something along these lines? (I.e. "eh, no, we do not want sidewalk on cycleways generally even if there are kerbs")

I can link as many comments to new users asking on Polish Forum/Telegram/Discord how to tag segregated cycleways and noone proposing to tag them as sidewalks.

I never really discussed that topic and my first contact with that tagging style was in  #3785 where I was completely confused (despite being quite involved in cycleway infrastructure tagging)

**Comment by matkoniecz** [comment]
I can start some review thread if that would be useful.

**Comment by westnordost** [comment]
What is a review thread?

**Comment by matkoniecz** [comment]
Tread on tagging mailing list or this new community site asking people how they would tag such feature and which tagging schemes are in normal use (or accepted) in their area.

**Comment by westnordost** [comment]
Doesn't really matter. "Cycleway with sidewalk" describes accurately a category of ... err bicycle road... in the Netherlands. Hm. This kind of touches on the the "bicycle road" topic I brought up in the forum.

**Comment by mnalis** [comment]
While I can't really provide input on code itself, here is my opinion about this segregated cycleway debate:

- if there are multiple schemas to describe some situation, both should be detected when reading the data
- unless the user is explicitly making a change, no writing of (e.g. rewritten to other schema) should occur
- if user is explicitly making a change, a **more common schema should be written**. 
  **Alternatively**, if it _very important_ not to do it in some country (e.g. if incompatible with Netherlands community mapping practices or something):
    -  either disable that overlay (or better yet _just that problematic answer_) **_in that country_** only, or
    -  implement code so alternative schema can be specified per-country

**Comment by westnordost** [comment]
As I wrote before having different tagging in different countries for the same physical thing does not make sense and nothing I want to endorse in this app. Different legal concepts and thus different ways to designate something, that's fine. But to have a situation where the same physical thing if boxed into a container and dumped into another country should then be tagged differently is untenable.

**Comment by mnalis** [comment]
> As I wrote before having different tagging in different countries for the same physical thing does not make sense and nothing I want to endorse in this app

I agree. That's why I mentioned it only as a **least preferred** alternative (i.e. just to note that such possibility exists)

File: app/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -1586,6 +1564,21 @@ Partially means that a wheelchair can enter and use the restroom, but no handrai
...
+    <string name="bicycle_boulevard_is_a">It’s a %1$s</string>
+    <string name="bicycle_boulevard_is_not_a">It’s not a %1$s</string>
+    <string name="bicycle_boulevard">Bicycle boulevard</string>
+    <string name="separate_cycleway_no">No cycling</string>
+    <string name="separate_cycleway_allowed">Cyclists are allowed</string>
+    <string name="separate_cycleway_no_or_allowed">Not designated for cyclists (regardless of whether cycling is allowed or not) </string>
+    <string name="separate_cycleway_non_segregated">Designated combined foot- and cycleway</string>
+    <string name="separate_cycleway_segregated">Segregated cycle- and footway</string>
+    <string name="separate_cycleway_exclusive">Exclusive cycleway</string>
+    <string name="separate_cycleway_with_sidewalk">Exclusive cycleway with sidewalk (footway is segregated from cycleway by a kerb)</string>
```
Comment (matkoniecz) [inline app/src/main/res/values/strings.xml:1577]: Maybe name it "cycleway has a sidewalk for foot traffic"?

So cases where it is clearly cycleway with sidewalk like https://community-cdn.openstreetmap.org/uploads/default/original/2X/0/0e3af26fdddf2ece75e97c6c0ca5c1e549e38273.jpeg from https://community.openstreetmap.org/t/deprecate-key-cyclestreet/6084/42 will be marked with this.

And infrastructure on edge between them, like https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg will be tagged depending on local preferences (depending on is it considered as segregated footway+cycleway or cycleway with sidewalk)

And cases like https://commons.wikimedia.org/wiki/File:30111VoieVerte1248.JPG will be always tagged as segregated footway and cycleway

Maybe name it "wide cycleway that has a sidewalk for foot traffic"?

Comment (westnordost) [reply app/src/main/res/values/strings.xml:1577]: What's wrong with the current string?

**Comment by matkoniecz** [comment]
> Another thing that I could add is to not show missing cycleways in 30 zones as missing.

Definitely makes sense. Maybe with exception of `oneway=yes` ones. Maybe only for contraflow side.

File: app/src/main/res/values/strings.xml (hunk 3 above)
Comment (matkoniecz) [reply app/src/main/res/values/strings.xml:1577]: Claims/implies that https://wiki.openstreetmap.org/wiki/File:Witosa_bike_2.jpg is mapped incorrectly if tagged

```
highway=path
segregated=yes
bicycle=designated
foot=designated
```

Comment (westnordost) [reply app/src/main/res/values/strings.xml:1577]: Moving in circles here. It does not claim it is mapped incorrectly. "Segregated cycle- and footway" is correct, too.
