### PR TITLE
Incorrect tactile paving option for crossings

### LINKED ISSUE #3813: Allow tagging tactile_paving=incorrect for when only one side of a crossing has it
**Use case**
It affects also crossing ques, but is `no` really correct when only one side has paving?

_Originally posted by @matkoniecz in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1039607154_

Probably `incorrect` is the right thing there. The wiki has "or if only one sloped kerb at a crossing has tactile paving" as an example of `incorrect`.

_Originally posted by @arrival-spring in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1039612736_

OT, but I'd appreciate some clarity/a new option for this (I normally just tag no as it's not yes). Also on a crossing with an island, if its only on either side but not on the island which is right?

_Originally posted by @peternewman in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1040544178_

There was a bit of a discussion here: https://github.com/streetcomplete/StreetComplete/issues/2738

I'd support having an other answers button of "Tactile paving only at the top or only at the bottom" and similarly for the crossing quest "Tactile paving only on one side" which would tag `incorrect` after a confirmation.

_Originally posted by @arrival-spring in https://github.com/streetcomplete/StreetComplete/issues/3762#issuecomment-1040650287_

See also #2738 .

I appreciate incorrect is low usage currently (0.11%) but I don't know about others but I'd certainly have been tagging no when it's only on one side (given "Does this crosswalk have tactile pavings on both sides?") although I'm not sure how many of those I've had. 

As mentioned I've also been tagging no if it's on the kerbs but not on the island as it's not on both sides of the two crossings, but I appreciate that probably needs a more general tagging discussion to find out what is the "correct" answer, or asking a blind person. @matkoniecz do you have contacts/feedback from your tactile maps?

**Proposed Solution**
Add an other answer for only on one side of the crossing

### PR DESCRIPTION
**Pull request by arrival-spring**
Fixes #3813 

As the same form is used for all tactile paving quests, showing the incorrect option only for nodes with `highway=crossing` or `highway=traffic_signals` (in the same way as the steps answer option in path quests) seemed like the best way of doing it.

### CODE REVIEW

**Review by matkoniecz — APPROVED** [review]
tested, works fine (is not appearing for kerb quests, as expected)

And big thanks for implementing it!

**Comment by matkoniecz** [comment]
And big thanks for implementing it!

**Comment by westnordost** [comment]
I was about to comment about that, because answering "on one side only" does not make sense when the app asks about just one kerb or just a bus stop. It is confusing to have such an answer option when it is not used.

Please instead just create a `TactilePavingCrosswalkForm` and leave the old `TactilePavingForm` as is. It may actually be less code this way.

**Comment by arrival-spring** [comment]
Fair enough

Tested and working as expected

File: app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingCrosswalkForm.kt [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+    override val contentLayoutResId = R.layout.quest_tactile_paving
+
+    override val otherAnswers get() = listOfNotNull(
+        createIncorrectAnswerItem()
+    )
+
+    private fun createIncorrectAnswerItem(): AnswerItem {
+        return AnswerItem(R.string.quest_tactilePaving_incorrect) { applyAnswer(INCORRECT) }
+    }
```
Comment (westnordost) [inline app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingCrosswalkForm.kt:20]:
```suggestion
    override val otherAnswers get() = listOf(
        AnswerItem(R.string.quest_tactilePaving_incorrect) { applyAnswer(INCORRECT) }
    )
```

File: app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingAnswer.kt [hunk 2]
```diff
@@ -0,0 +1,7 @@
+package de.westnordost.streetcomplete.quests.tactile_paving
+
+enum class TactilePavingAnswer(val osmValue: String) {
```
Comment (westnordost) [inline app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingAnswer.kt:3]: It would be consistent if this was named `TactilePavingCrosswalkAnswer`. Not a merge blocker though.

**Review by westnordost — APPROVED** [review]
It is actually less code than before :-)

Thank you for doing this change!

File: app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingAnswer.kt (hunk 2 above)
Comment (arrival-spring) [reply app/src/main/java/de/westnordost/streetcomplete/quests/tactile_paving/TactilePavingAnswer.kt]: Done

**Comment by arrival-spring** [comment]
Thanks for doing the shortening, could have sworn I'd already done that!
